import 'dart:convert';

import 'package:flutter_test/flutter_test.dart';
import 'package:keywallet_multios/core/crypto/kwv1_crypto.dart';

// Generated by the actual Go KeyWallet 0.1.4 encryptBlob() implementation.
// Password: go-flutter-fixture
// Revision: 42
const _go014Fixture =
    'S1dWMegDAAAqAAAAAAAAACoqKioqKioqKioqKioqKirRPH9xT7QmY8+jek9zY2HxS3hfcHsUU2nU5FzqbnG/fPPUvyN7CKqo9NS0iOWa2jP5PUldIP1WeH+JL4ImqJ0c5Lkf6lu7LJzTKIrJEgpTUHJPF3TJZsuUM59T4SrnnSlnAcbA9pQDq1nIhuIsDyclKIjMC/AN7xu7HoB5jWIup02Oy/v7lizQiHiejZJPh60Zovhi4v/YbqQQxpyfGsAkxpCjEuFLm25PxVk0ZJu2V6X9oMDyTCED3BzVlVyRFXm7PXH1UGIyoh8t15iHIsSY5eqVO7U9URuwXN7Tw4mq8uLVZp26Bg8fU8ddwOrOXbxtMhIVjGNZ1pmY2A3a42FZT5CoikY4+6u+Gb9Fn2GdE5WvjSv+Uww047HLwHXPO2i6+k18l7Ozgr9fNbxRZz/Y6qs7RWdW3ht3y6pjCpAk1xSpzszhd9pRbtRkjDVmVqT+OI+7QF7Y+kebT9nO9dQwH7EtClcZ/S63RZ2IcCa0XIcku1mzfAPDZZBhfUXaJIBaDACr6508z4SaQE/bQz6b5ISbXCo07avT/0ha9lYu5EpgtFf8VsF7QrjbVG1OiU2nb5qsXLQjSyfi/kWgT4NkmsW0/WMAs8WNBjEPYzgPm3WGJQWKZ0ZY5DzriO0xrwq633a5gR6hiFORVXtdEjIs2owh8fDNBLnyRGtGZMrQQWYs6czE9bV1f873cOC0ZM3dN1chM1KeDFF16+L2RuxMooZ4VXqSgcUJwCE35QT7HOfQ9j+vWoWEIvk34/EqxoC/SXK5LVDeoLzSZQ==';

void main() {
  test('decrypts a vault produced by Go KeyWallet 0.1.4', () async {
    final opened = await Kwv1Crypto.decrypt(
      base64Decode(_go014Fixture),
      'go-flutter-fixture',
    );

    expect(opened.container.iterations, 1000);
    expect(opened.container.revision, 42);
    expect(opened.vault.version, 1);

    final git = opened.vault.root.children.single;
    expect(git.name, 'GIT');
    final entry = git.children.single;
    expect(entry.kind, 'github-ssh');
    expect(entry.meta['algorithm'], 'Ed25519');
    expect(entry.meta['comment'], 'fixture@example.com');
    expect(entry.files.length, 2);
    expect(
      utf8.decode(entry.files.first.data),
      'ssh-ed25519 AAAATEST fixture@example.com\n',
    );
    expect(utf8.decode(entry.files.last.data), 'PRIVATE-FIXTURE');
  });
}
